import { Activity } from './types';
import { getTodayString } from './utils';

export function getSampleActivities(): Activity[] {
  const today = getTodayString();
  const getRelativeDate = (offsetDays: number): string => {
    const d = new Date();
    d.setDate(d.getDate() + offsetDays);
    const year = d.getFullYear();
    const month = String(d.getMonth() + 1).padStart(2, '0');
    const day = String(d.getDate()).padStart(2, '0');
    return `${year}-${month}-${day}`;
  };

  return [
  // 1. Candidate Sourcing Pipeline
  {
    id: 'act_101',
    tenantId: 'org_default',
    title: 'Senior Frontend Engineer - LinkedIn & Portal Sourcing',
    description: 'Screen 25+ applicant profiles for Next.js & TypeScript proficiency, shortlist top 5.',
    category: 'candidate_sourcing',
    stage: 'sourcing',
    status: 'under_processing',
    priority: 'high',
    plannedDate: today,
    plannedStartTime: '10:00',
    plannedHours: 2.5,
    actualHours: 2.0,
    actualNotes: 'Reviewed 18 profiles, 4 shortlisted for initial round.',
    hasReminder: true,
    reminderTime: `${today}T09:45`,
    deadline: `${today}T18:00`,
    approverName: 'Meera Nambiar',
    approverRole: 'VP - Human Resources',
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      candidateRole: 'Senior Frontend Engineer',
      reportPeriod: 'Q3',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_102',
    tenantId: 'org_default',
    title: 'Candidate Follow-Up: Lead Architect (Rohit Malhotra)',
    description: 'Follow up on counter-offer status and confirm joining timeline acceptance.',
    category: 'candidate_sourcing',
    stage: 'follow_up',
    status: 'planned',
    priority: 'urgent',
    plannedDate: today,
    plannedStartTime: '11:30',
    plannedHours: 1.0,
    actualHours: 0,
    hasReminder: true,
    reminderTime: `${today}T11:15`,
    deadline: `${today}T16:00`,
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      candidateName: 'Rohit Malhotra',
      candidateRole: 'Lead Architect',
      candidateContact: '+91 98765 43210',
      ctcOffered: '38 LPA',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_103',
    tenantId: 'org_default',
    title: 'Expected Joining Verification: QA Automation Lead',
    description: 'Coordinate background verification sign-off and welcome kit for joining next Monday.',
    category: 'candidate_sourcing',
    stage: 'expected_joining',
    status: 'planned',
    priority: 'medium',
    plannedDate: getRelativeDate(2),
    plannedStartTime: '14:00',
    plannedHours: 1.5,
    actualHours: 0,
    hasReminder: true,
    reminderTime: `${getRelativeDate(2)}T13:30`,
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      candidateName: 'Pooja Iyer',
      expectedJoiningDate: getRelativeDate(2),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_104',
    tenantId: 'org_default',
    title: 'New Joinee Induction: DevOps Specialist (Ananya Sen)',
    description: 'Conduct Day 1 onboarding presentation, IT asset handover, and team introduction.',
    category: 'candidate_sourcing',
    stage: 'joining',
    status: 'completed',
    priority: 'high',
    plannedDate: today,
    plannedStartTime: '09:30',
    plannedHours: 2.0,
    actualHours: 2.0,
    actualNotes: 'Induction completed successfully, laptop configured and access permissions provisioned.',
    hasReminder: true,
    reminderTime: `${today}T09:15`,
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      candidateName: 'Ananya Sen',
      candidateRole: 'DevOps Specialist',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 2. Reports Pipeline
  {
    id: 'act_201',
    tenantId: 'org_default',
    title: 'Monthly HR Analytics & Headcount Reconciliation Report',
    description: 'Consolidate attrition rate, department headcount shifts, and cost-per-hire metrics for August.',
    category: 'reports',
    stage: 'processing',
    status: 'under_processing',
    priority: 'high',
    plannedDate: today,
    plannedStartTime: '14:00',
    plannedHours: 3.0,
    actualHours: 1.5,
    actualNotes: 'Data pulled from HRIS, drafting executive summary slide deck.',
    hasReminder: true,
    reminderTime: `${today}T13:45`,
    deadline: `${today}T19:00`,
    approverName: 'Rajesh Sharma',
    approverRole: 'Managing Director / CEO',
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      reportType: 'Headcount & Attrition Analytics',
      reportPeriod: 'August 2026',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_202',
    tenantId: 'org_default',
    title: 'Quarterly Overtime & Compliance Report - Sign-off',
    description: 'Submitted to VP HR and Managing Director for top-level review and sign-off.',
    category: 'reports',
    stage: 'submitted_for_approval',
    status: 'waiting_approval',
    priority: 'urgent',
    plannedDate: getRelativeDate(-2), // Submitted 2 days ago
    plannedStartTime: '15:00',
    plannedHours: 2.0,
    actualHours: 2.0,
    hasReminder: false,
    deadline: `${today}T17:00`,
    approverName: 'Meera Nambiar',
    approverRole: 'VP - Human Resources',
    approvalStatus: 'pending',
    approvalNotes: 'Awaiting final verification on factory shift overtime calculations.',
    postponeCount: 0,
    metadata: {
      reportType: 'Overtime & Labor Compliance',
      reportPeriod: 'Q2',
    },
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'act_203',
    tenantId: 'org_default',
    title: 'Weekly Recruitment Pipeline Funnel Summary',
    description: 'Compile conversion rates from sourcing to technical interview and offer releases.',
    category: 'reports',
    stage: 'completed',
    status: 'completed',
    priority: 'medium',
    plannedDate: today,
    plannedStartTime: '09:00',
    plannedHours: 1.5,
    actualHours: 1.2,
    actualNotes: 'Completed ahead of time and circulated via email to hiring managers.',
    hasReminder: false,
    approvalStatus: 'approved',
    approverName: 'Meera Nambiar',
    approverRole: 'VP - Human Resources',
    postponeCount: 0,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 3. Statutory Compliance Pipeline
  {
    id: 'act_301',
    tenantId: 'org_default',
    title: 'Provident Fund (PF) ECR Monthly Challan Filing',
    description: 'Generate electronic challan return (ECR) for August wages, upload to EPFO portal.',
    category: 'statutory',
    stage: 'processing',
    status: 'under_processing',
    priority: 'urgent',
    plannedDate: today,
    plannedStartTime: '11:00',
    plannedHours: 2.0,
    actualHours: 1.0,
    hasReminder: true,
    reminderTime: `${today}T10:45`,
    deadline: `${today}T16:00`,
    approverName: 'Anand Kulkarni',
    approverRole: 'Chief Financial Officer (CFO)',
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      statutoryType: 'PF',
      filingDueDate: `${today}`,
      challanNumber: 'ECR-2026-08-9841',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_302',
    tenantId: 'org_default',
    title: 'Professional Tax (PT) Half-Yearly Return - Executive Approval',
    description: 'Draft return prepared with state-wise breakup. Pending CFO authorization for remittance.',
    category: 'statutory',
    stage: 'submitted_for_approval',
    status: 'waiting_approval',
    priority: 'high',
    plannedDate: getRelativeDate(-4), // 4 days ago -> Long Under Processing
    plannedStartTime: '16:00',
    plannedHours: 2.5,
    actualHours: 2.5,
    hasReminder: false,
    deadline: `${today}T15:00`,
    approverName: 'Anand Kulkarni',
    approverRole: 'Chief Financial Officer (CFO)',
    approvalStatus: 'pending',
    approvalNotes: 'Draft submitted 4 days ago. Reminded CFO office for digital signature.',
    postponeCount: 0,
    metadata: {
      statutoryType: 'PT',
      filingDueDate: getRelativeDate(2),
    },
    createdAt: new Date(Date.now() - 4 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 86400000).toISOString(),
  },
  {
    id: 'act_303',
    tenantId: 'org_default',
    title: 'ESI Monthly Statutory Contribution & Challan Reconciliation',
    description: 'Verify employee and employer contributions across all 4 regional establishments.',
    category: 'statutory',
    stage: 'yet_to_prepare',
    status: 'planned',
    priority: 'medium',
    plannedDate: getRelativeDate(1), // Tomorrow
    plannedStartTime: '10:30',
    plannedHours: 2.0,
    actualHours: 0,
    hasReminder: true,
    reminderTime: `${getRelativeDate(1)}T10:00`,
    deadline: `${getRelativeDate(3)}T17:00`,
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      statutoryType: 'ESI',
      filingDueDate: getRelativeDate(3),
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 4. Payroll Pipeline (Addition, Deletion, Separation, Transfer)
  {
    id: 'act_401',
    tenantId: 'org_default',
    title: 'Payroll Addition: Process 8 New Joinees into Salary Register',
    description: 'Verify bank details, PAN, UAN and CTC structures for August joinees.',
    category: 'payroll',
    stage: 'addition',
    status: 'completed',
    priority: 'high',
    plannedDate: today,
    plannedStartTime: '10:00',
    plannedHours: 3.0,
    actualHours: 2.5,
    actualNotes: 'All 8 profiles uploaded into payroll engine, verified with HRMS.',
    hasReminder: false,
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      payrollSubtype: 'addition',
      reportPeriod: 'September 2026',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_402',
    tenantId: 'org_default',
    title: 'Payroll Separation: Full & Final (FnF) Clearance for 2 Exiting Engineers',
    description: 'Calculate leave encashment, gratuity eligibility, and asset return clearance.',
    category: 'payroll',
    stage: 'separation',
    status: 'waiting_approval',
    priority: 'urgent',
    plannedDate: today,
    plannedStartTime: '15:30',
    plannedHours: 2.0,
    actualHours: 1.8,
    hasReminder: true,
    reminderTime: `${today}T15:15`,
    deadline: `${today}T18:30`,
    approverName: 'Meera Nambiar',
    approverRole: 'VP - Human Resources',
    approvalStatus: 'pending',
    approvalNotes: 'FnF computation sheet attached. Awaiting VP sign-off.',
    postponeCount: 0,
    metadata: {
      payrollSubtype: 'separation',
      employeeName: 'Vikrant Deshmukh & S. Karthik',
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_403',
    tenantId: 'org_default',
    title: 'Payroll Transfer: Relocation Cost & Branch Payroll Shift (Chennai to Bengaluru)',
    description: 'Adjust state tax liability and transfer employee master records between cost centers.',
    category: 'payroll',
    stage: 'transfer',
    status: 'postponed',
    priority: 'medium',
    plannedDate: getRelativeDate(1), // Postponed to tomorrow
    originalPlannedDate: getRelativeDate(-1),
    plannedStartTime: '14:30',
    plannedHours: 1.5,
    actualHours: 0,
    hasReminder: true,
    reminderTime: `${getRelativeDate(1)}T14:00`,
    earlierReminderTime: `${getRelativeDate(1)}T09:00`, // Advance reminder configured!
    postponeCount: 1,
    postponeReason: 'Pending branch clearance certificate from Chennai facility admin.',
    approvalStatus: 'none',
    metadata: {
      payrollSubtype: 'transfer',
      employeeName: 'Divya Nair',
    },
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_404',
    tenantId: 'org_default',
    title: 'Payroll Deletion: Unpaid Leave (LOP) & Exit Deductions Audit',
    description: 'Audit 6 cases of mid-month resignation and attendance discrepancies.',
    category: 'payroll',
    stage: 'deletion',
    status: 'planned',
    priority: 'low',
    plannedDate: getRelativeDate(-5), // 5 days ago -> Long Pending
    plannedStartTime: '16:00',
    plannedHours: 2.0,
    actualHours: 0,
    hasReminder: false,
    approvalStatus: 'none',
    postponeCount: 0,
    metadata: {
      payrollSubtype: 'deletion',
    },
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },

  // 5. Engagement Activities & Event Planning
  {
    id: 'act_501',
    tenantId: 'org_default',
    title: 'Q3 Town Hall & Rewards Recognition (R&R) Assembly',
    description: 'Finalize auditorium booking, audio-visual testing, award trophies, and catering vendor.',
    category: 'engagement',
    stage: 'planning',
    status: 'under_processing',
    priority: 'high',
    plannedDate: today,
    plannedStartTime: '16:30',
    plannedHours: 2.0,
    actualHours: 1.0,
    actualNotes: 'Auditorium booked. Award citations collected from department managers.',
    hasReminder: true,
    reminderTime: `${today}T16:15`,
    deadline: `${getRelativeDate(3)}T17:00`,
    approverName: 'Pooja Verma',
    approverRole: 'Director - Operations',
    approvalStatus: 'approved',
    postponeCount: 0,
    metadata: {
      eventVenue: 'Main Auditorium & Hybrid Zoom Stream',
      budgetAllocated: 120000,
      expectedParticipants: 350,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'act_502',
    tenantId: 'org_default',
    title: 'Annual Hackathon & Innovation Showcase - Budget Proposal',
    description: 'Draft budget for 2-day hackathon, external mentors, prize pool, and merchandise.',
    category: 'engagement',
    stage: 'ideation',
    status: 'waiting_approval',
    priority: 'urgent',
    plannedDate: getRelativeDate(4),
    plannedStartTime: '11:00',
    plannedHours: 2.5,
    actualHours: 0,
    hasReminder: true,
    reminderTime: `${getRelativeDate(4)}T10:00`,
    deadline: `${getRelativeDate(5)}T18:00`,
    approverName: 'Rajesh Sharma',
    approverRole: 'Managing Director / CEO',
    approvalStatus: 'pending',
    approvalNotes: 'Proposal submitted to CEO for financial approval of INR 4.5 Lakhs.',
    postponeCount: 0,
    metadata: {
      budgetAllocated: 450000,
      expectedParticipants: 180,
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  ];
}

export const INITIAL_ACTIVITIES: Activity[] = getSampleActivities();

export const INITIAL_ORGANIZATIONS = [
  {
    id: 'org_default',
    name: 'Acme Global Operations',
    slug: 'acme-global',
    plan: 'enterprise',
    ownerId: 'user_admin',
    ownerEmail: 'admin@acmecorp.com',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'org_techcorp',
    name: 'TechCorp Innovations',
    slug: 'techcorp-innovations',
    plan: 'pro',
    ownerId: 'user_tech',
    ownerEmail: 'hr@techcorp.io',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_MEMBERSHIPS = [
  {
    id: 'mem_default_admin',
    tenantId: 'org_default',
    userId: 'user_admin',
    userName: 'Santheep (Admin)',
    userEmail: 'admin@acmecorp.com',
    role: 'admin' as const,
    department: 'People Operations',
    designation: 'VP of HR Operations',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'mem_techcorp_admin',
    tenantId: 'org_techcorp',
    userId: 'user_admin',
    userName: 'Santheep (Admin)',
    userEmail: 'admin@acmecorp.com',
    role: 'manager' as const,
    department: 'Talent Acquisition',
    designation: 'HR Lead',
    isActive: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
